Upgrade to **autonomous** CEv1,
Palindrom/palindrom-redirect pull request #9
Opened 2018-01-04 22:43 UTC by tomalec

Remove `puppet-redirect` backward compatibility layer.

Problem: it was not working with latest WebComponents.js polyfill

Required for https://github.com/Starcounter/StarcounterClientFiles/pull/22

2018-01-04 22:49 UTC, alshakero requested changes

2018-01-04 22:49 UTC, alshakero commented on palindrom-redirect.html
> +            debugger
~~debugger~~

2018-01-04 22:49 UTC, alshakero commented on palindrom-redirect.html
> +                      `${this.localName}-pushstate`,
This can be changed to static `palindrom-redirect-pushstate` now backward compat is killed.

2018-01-04 22:59 UTC, alshakero commented
This is a static review. Tomorrow morning I'll test it.

2018-01-04 23:13 UTC, warpech approved these changes
Other than @alshakero's comments, I have tested it locally with https://github.com/StarcounterApps/SignIn/commit/417ffece11b6ba0ff1acc59a77683d8f801d3fa2 and https://github.com/Starcounter/StarcounterClientFiles/pull/22 in Chrome and Firefox and it worked OK.

2018-01-04 23:16 UTC, alshakero approved these changes
Since @warpech tested.

2018-01-04 23:31 UTC, merged

2018-01-04 23:39 UTC, tomalec commented
Released at https://github.com/Palindrom/palindrom-redirect/releases/tag/1.0.0

2018-01-09 15:50 UTC, warpech commented
Setting as Finished because it is:

- properly released in the version https://github.com/Palindrom/palindrom-redirect/releases/tag/1.0.0 that has a proper description
- included in https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.1
- included in levlel1 develop https://github.com/Starcounter/level1/pull/4435/files
- mentioned in a blog post https://starcounter.io/starcounter-2-4-gets-upgrade-polymer-2/